export const CONVERSATION_USER_HISTORY_CONVERSATION = '[CONVERSATION] USER_HISTORY_CONVERSATION';

export const CONVERSATION_SUCCESS = '[CONVERSATION] SUCCESS';
export const CONVERSATION_FAIL = '[CONVERSATION] FAIL';
export const CONVERSATIONS_USER_CONVERSATIONS = '[CONVERSATION] USER CONVERSATIONS';

export const GET_LAST_CONVERSATION_MESSAGE = '[CONVERSATION] GET LAST CONVERSATION MESSAGE';
