export const CONVERSATION_USER_HISTORY_CONVERSATION = '[CONVERSATION] USER_HISTORY_CONVERSATION';

export const CONVERSATION_SUCCESS = '[CONVERSATION] SUCCESS';
export const CONVERSATION_FAIL = '[CONVERSATION] FAIL';
export const CONVERSATIONS_USER_CONVERSATIONS = '[CONVERSATION] USER CONVERSATIONS';
export const CONVERSATIONS_ADD_NEW_MESSAGE = '[CONVERSATION] ADD NEW MESSAGE';
export const GET_LAST_CONVERSATION_MESSAGE = '[CONVERSATION] GET LAST CONVERSATION MESSAGE';
export const CONVERSATION_ID = '[CONVERSATIONS] CONVERSATION ID';
export const CONVERSATION_TYPE_STATE = '[CONVERSATIONS] CONVERSATION TYPE STATE';
export const CONVERSATION_CREATE_NEW_CONVERSATION = '[CONVERSATION] CREATE NEW CONVERSATION';
export const CONVERSATION_CLEAR_DATA = '[CONVERSATION] CLEAR DATA';
