export const APP_PRELOADER = 'APP PRELOADER';
export const SHOW_CONTEXT_MENU = 'SHOW CONTEXT MENU';
export const IS_EDIT_MESSAGE = 'IS EDIT MESSAGE';
export const IS_DELETE_MESSAGE = 'IS DELETE MESSAGE';
