export const APP_PRELOADER = 'APP PRELOADER';
export const SHOW_CONTEXT_MENU = 'SHOW CONTEXT MENU';
export const IS_EDIT_MESSAGE = 'IS EDIT MESSAGE';
export const SHARE_MESSAGES = 'SHARE MESSAGES';
export const IS_DELETE_MESSAGE = 'IS DELETE MESSAGE';
export const DIALOG_COMPONENT_SHOW = 'DIALOG COMPONENT SHOW';
export const DIALOG_COMPONENT_HIDDEN = 'DIALOG COMPONENT HIDDEN';
export const SET_LANGUAGE = '[LANGUAGE] SET LANGUAGE';
