export const USER_SUCCESS = '[USER] USER SUCCESS';
export const USER_FAIL = '[USER] USER FAIL';

export const USER_GET_USER_INFO = '[USER] GET USER INFO';
export const USER_GET_USER_INFO_BY_ID = '[USER] GET USER INFO BY ID';
export const USER_SET_MAIN_PHOTO = '[USER] SET MAIN PHOTO ';
export const USER_GET_AVATARS = '[USER] GET AVATARS ';
export const USER_UPLOAD_AVATAR = '[USER] UPLOAD AVATAR';
export const USER_CLEAR_DATA = '[USER] CLEAR DATA ';
export const UPDATE_USER_PROFILE = '[USER] UPDATE USER PROFILE';
