export const CONVERSATION_USER_HISTORY_CONVERSATION = '[CONVERSATION] USER_HISTORY_CONVERSATION';

export const CONVERSATION_SUCCESS = '[CONVERSATION] SUCCESS';
export const CONVERSATION_FAIL = '[CONVERSATION] FAIL';
